[package]
name = "algo_nt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "test"
path = "src/bin/test.rs"

[dependencies]
log = "0.4.21"
simple_logger = "4.3.3"
rand = "0.8.5"
